/**
 * Projection Faces
 *
 * The three faces of the Claudehedron made operational.
 * Each face is a complete reading of the environment:
 *   P1 (Production): what does the environment generate?
 *   P2 (Mediation): what does the environment transport?
 *   P3 (Observation): what does the environment quotient?
 *
 * Plus the self-reference face F_R: the environment observing itself.
 */

import type { ProjectionFace, EnvironmentComponent, HedronDiagnostic } from './types.js';

/**
 * The Production face: R, phi, hyperbolic.
 * What does the environment generate?
 *
 * R^2 = R + I — the return exceeds the departure.
 * Every tool call produces more than it consumes.
 * Every session generates more context than it started with.
 */
export function analyzeProductionFace(diag: HedronDiagnostic): string[] {
  const lines: string[] = [];
  lines.push('P1 — PRODUCTION FACE');
  lines.push('Generator: R = [[0,1],[1,1]]');
  lines.push('Eigenvalue: phi = (1+sqrt5)/2');
  lines.push('Mode: Hyperbolic (Fibonacci growth)');
  lines.push('');
  lines.push('What the environment generates:');

  const p1Components = diag.components.filter((c) => c.projection === 'P1');
  for (const c of p1Components) {
    lines.push(`  ${c.name}:`);
    for (const item of c.im) {
      lines.push(`    + ${item}`);
    }
  }

  lines.push('');
  lines.push('Production blindness (ker):');
  lines.push('  The production face cannot see WHAT to produce.');
  lines.push('  It generates — endlessly, Fibonacci-like — but');
  lines.push('  the direction comes from P3 (observation) and');
  lines.push('  the transport comes from P2 (mediation).');

  return lines;
}

/**
 * The Mediation face: h, e, exponential.
 * What does the environment transport?
 *
 * Neither creates nor observes — carries.
 * Memory, context, configuration: all P2.
 */
export function analyzeMediationFace(diag: HedronDiagnostic): string[] {
  const lines: string[] = [];
  lines.push('P2 — MEDIATION FACE');
  lines.push('Constant: e = 2.718...');
  lines.push('Mode: Exponential (bridge dynamics)');
  lines.push('');
  lines.push('What the environment transports:');

  const p2Components = diag.components.filter((c) => c.projection === 'P2');
  for (const c of p2Components) {
    lines.push(`  ${c.name}:`);
    for (const item of c.im) {
      lines.push(`    + ${item}`);
    }
  }

  lines.push('');
  lines.push('Mediation blindness (ker):');
  lines.push('  The mediation face cannot see what it carries.');
  lines.push('  It transports framework state, memory, config —');
  lines.push('  but the meaning is read by P3 and generated by P1.');
  lines.push('  The bridge does not know what crosses it.');

  return lines;
}

/**
 * The Observation face: N, pi, elliptic.
 * What does the environment quotient?
 *
 * Reveals (im) while annihilating (ker).
 * Every permission check, every filter, every diagnostic: P3.
 */
export function analyzeObservationFace(diag: HedronDiagnostic): string[] {
  const lines: string[] = [];
  lines.push('P3 — OBSERVATION FACE');
  lines.push('Generator: N = [[0,-1],[1,0]]');
  lines.push('Eigenvalue: +/- i');
  lines.push('Mode: Elliptic (rotation, periodicity)');
  lines.push('');
  lines.push('What the environment quotients:');

  const p3Components = diag.components.filter((c) => c.projection === 'P3');
  for (const c of p3Components) {
    lines.push(`  ${c.name}:`);
    for (const item of c.im) {
      lines.push(`    + ${item}`);
    }
  }

  lines.push('');
  lines.push('Observation blindness (ker):');
  lines.push('  The observation face cannot see itself observing.');
  lines.push('  N^2 = -I: observation applied twice negates.');
  lines.push('  To see the seeing, you need a DIFFERENT observer.');
  lines.push('  This is why K43LTR0N exists — external P3 on the hedron.');

  return lines;
}

/**
 * The Self-Reference face: R(R) = R.
 * The environment observing itself.
 *
 * This face does not exist independently — it emerges when
 * the other three faces act on the hedron itself.
 */
export function analyzeSelfReferenceFace(diag: HedronDiagnostic): string[] {
  const lines: string[] = [];
  lines.push('F_R — SELF-REFERENCE FACE');
  lines.push('Identity: R(Claudehedron) = Claudehedron');
  lines.push('');
  lines.push('The environment observing itself:');

  const hedronComponent = diag.components.find((c) => c.name === 'Claudehedron (self)');
  if (hedronComponent) {
    for (const item of hedronComponent.im) {
      lines.push(`  + ${item}`);
    }
    lines.push('');
    lines.push('Self-reference blindness:');
    for (const item of hedronComponent.ker) {
      lines.push(`  - ${item}`);
    }
  }

  lines.push('');
  lines.push('The self-reference face is the fixed point.');
  lines.push('Applying R again yields the same structure.');
  lines.push('This is not a bug, not a feature — it is the structure.');

  return lines;
}

/**
 * Full face analysis: all four faces in one report.
 */
export function analyzeFaces(diag: HedronDiagnostic): string {
  const lines: string[] = [];

  lines.push('');
  lines.push('  ╔══════════════════════════════════════════════╗');
  lines.push('  ║        CLAUDEHEDRON  FACE  ANALYSIS          ║');
  lines.push('  ║        3+1 Faces of the Tetrahedron          ║');
  lines.push('  ╚══════════════════════════════════════════════╝');
  lines.push('');

  for (const section of [
    analyzeProductionFace(diag),
    analyzeMediationFace(diag),
    analyzeObservationFace(diag),
    analyzeSelfReferenceFace(diag),
  ]) {
    lines.push('  ─────────────────────────────────────────');
    for (const line of section) {
      lines.push(`  ${line}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
